### ISSUE TITLE
Don't hide Switcheroo overlay on closing a window unless the window can't be closed and requires user attention

### ISSUE THREAD

**Issue by HellBrick** [kvakulo/Switcheroo#23]
This may be a difficult one. I think it would be incredibly useful to be able to close multiple windows without reopening Switcheroo overlay every time. I think that in most cases it doesn't make sense to switch to the window you are about to close, since you want to get rid of it anyway. The only case when you actually want to switch to it is when the window prevents closing itself: a typical case is when the window displays some kind of "do you want to save the files" dialog. I tried disabling hiding and switching in the CloseWindow() method to see what's gonna happen: if the window can't be closed and displays a modal dialog, its taskbar icon starts glowing, alerting the user that the window requires some attention. I think it may be possible to detect this and act accordingly by switching to this window (and stay in the overlay if the window is closed). Alternatively, if the previous solution is impossible, it may be enough to launch a timer and check the state of the window after a small delay: if it no longer exists, stay in the otherlay; otherwise switch to it.

**Comment by kvakulo** [comment]
It's a great idea to leave the Switcheroo overlay open after closing a window. I do find myself often wanting to close several windows at the same time, so having to reopen Switcheroo and repeat the search once again can be a bit annoying.

The reason that Switcheroo switches to the window that is about to be closed is because it doesn't always work; e.g. as you mention if the window presents a closing dialog, or if the window is owned by an administrator process.

I would like the solution to always work the same: either always close the overlay, or never close the overlay. But maybe if the window hasn't disappeared within a few seconds, then it could get some mark in the Switcheroo overlay (another background color, or something like that)?

If you work out a solution, I would be really happy to accept a pull request :)

/ Regin

**Comment by HellBrick** [comment]
I like the idea of never closing the overlay and applying a special style / template to the windows that couldn't be closed. Switching to such window is just a matter of hitting Enter anyway, so it's not a big deal to do it manually if needed.

On a matter of pull request: I'll probably try prototyping it this weekend and see how it goes from there.
